### ISSUE TITLE
Main Branch

### ISSUE THREAD

**Issue by NiranjanAjith** [Eco-bins/Ecobins#6]
Isn't main branch old version made with django??

ippo react use cheyyanel pinne ath vendalo. delete aakikoode

**Comment by aioont** [comment]
> Isn't main branch old version made with django??
> 
> ippo react use cheyyanel pinne ath vendalo. delete aakikoode

Yes. You can delete it. Nee work cheyth vachond njn delete akknje annode choyikn vittu poyy.
